Using TensorFlow backend.
Traceback (most recent call last):
  File "./training-latplan.py", line 138, in <module>
    lyr.Constraint("forall x: is(x, SAE(x))")
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/lyrics.py", line 380, in __init__
    self.root.compile()
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/parser.py", line 555, in compile
    super(ForAll, self).compile()
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/parser.py", line 30, in compile
    i.compile()
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/parser.py", line 335, in compile
    i.compile()
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/parser.py", line 285, in compile
    self.tensor = self.function.function(*tensors)
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/functions.py", line 397, in __call__
    y,_ = self._internal_(x)
  File "/g100_work/uBS21_InfGer_0/lyrics/lyrics/functions.py", line 385, in _internal_
    latplan_model, error = task(parameters)
  File "../latplan/latplan/util/util.py", line 2, in <lambda>
    return lambda *args,**kwargs: fn(*args1,*args,**{**kwargs1,**kwargs})
  File "../latplan/latplan/util/tuning.py", line 172, in loadsNetWithWeightsGOOD
    keras.backend.clear_session()
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 107, in clear_session
    tf.reset_default_graph()
  File "/g100/home/userexternal/abarbin0/.conda/envs/latplan/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 5852, in reset_default_graph
    raise AssertionError("Do not use tf.reset_default_graph() to clear "
AssertionError: Do not use tf.reset_default_graph() to clear nested graphs. If you need a cleared graph, exit the nesting and create a new graph.
